### ISSUE TITLE
Add jq to tokei so lines-of-code-counter can work

### ISSUE THREAD

**Issue by glennj** [exercism/jq#112]
https://github.com/XAMPPRocky/tokei/blob/master/CONTRIBUTING.md#language-addition

**Comment by glennj** [comment]
Created PR XAMPPRocky/tokei#965

**Comment by ErikSchierboom** [comment]
Ping me when it is merged, and I'll make sure it'll work in the lines of code counter.

**Comment by ErikSchierboom** [comment]
I've redeployed the lines of code counter https://github.com/exercism/lines-of-code-counter/actions/runs/4830170017/jobs/8606057918 and have just scheduled the existing iterations for recalculation of their lines of code. They should all be done now.

**Comment by glennj** [comment]
Exercism can now count lines of code of jq files
