### ISSUE TITLE
Write docs for `functions` concept

### ISSUE THREAD

**Issue by glennj** [exercism/jq#12]

**Comment by legendarykamal** [comment]
hi @glennj I would like to work on this issue . /assign me

**Comment by glennj** [comment]
How comfortable are you with the `jq` language?

**Comment by legendarykamal** [comment]
@glennj Jquery? As in at an intermediate level.

**Comment by glennj** [comment]
No `jq`. This issue is in the `exercism/jq` repo. Please [read the docs](https://github.com/exercism/jq/tree/main/docs) first.
