### ISSUE TITLE
Review Syllabus and populate "practices" and "prerequisites" arrays for practice exercises

### ISSUE THREAD

**Issue by glennj** [exercism/jq#132]
The syllabus: do the prerequisites make sense?

![image](https://user-images.githubusercontent.com/122470/212707776-71af749b-0201-4704-8ee1-a02886874b07.png)

**Comment by IsaacG** [comment]
* If you have `Basics > Strings > Arrays`, do you also need `Basics > Arrays`?
* Should there be a link between `Objects` and `Arrays`?
* Why does `Comparison` depend on `Strings` but `Conditionals` depends on `Numbers`?
* Should `Comparison` be plural? Most of these are plural.
* Should `Reduce` and `Regexp` have similar dependencies on `Functions`?
* `Functions` depends on `Conditionals` but not on `Comparisons`. Should dependencies on those be similar?

**Comment by glennj** [comment]
Strings does not depend on Arrays. The lines go behind. On the Syllabus page, hovering over a concept reveals the connections.

Suggested changes
- Arrays and Objects need Strings and Numbers as prerequisites
- All the plurals are nouns. Reduce is a verb. => Comparison changed to Compare
- Variables depends on all the datatypes. Compare should as well
- Then Conditionals can depend just on Compare
- Do you think the student needs Functions to study the Reduce? But Reduce also needs Conditionals (base case versus recursion case)
- Regexp just needs Strings.

```none
Basics
Strings < Basics
Numbers < Basics
Arrays < (Strings, Numbers)
Objects < (Strings, Numbers)
Variables < (Arrays, Objects)
Compare < (Arrays, Objects)
Conditionals < Compare
Reduce < Variables
Functions < Variables
Recursion < (Functions, Conditionals)
Regexp < Strings
```

**Comment by glennj** [comment]
Alternately we could force a path through the datatypes
- Basics > Numbers > Strings > Arrays > Objects

Then Variables and Compare depend on Objects

**Comment by IsaacG** [comment]
I like the first proposal of `Basics > (Strings, Numbers) > (Arrays, Objects) > (Variables, Compare)` and all the rest.

> Do you think the student needs Functions to study the Reduce? But Reduce also needs Conditionals (base case versus recursion case)

I don't think Functions is needed for Reduce.

**Comment by glennj** [comment]
Syllabus now looks like this
![image](https://user-images.githubusercontent.com/122470/212775568-2ffad070-1f7f-48a9-b9e4-c7ade27e286e.png)
