### ISSUE TITLE
regular-chatbot:check_phone_number task needs input type clarification

### ISSUE THREAD

**Issue by phineas42** [exercism/jq#208]
Regarding the regular-chatbot exercise and its "Check Valid Phone Number" task:

There are discrepancies between the exercise instructions, the source code template comments, and the test definition for the "check_phone_number" function input type.

- The instructions suggest that the input description might be "chatbot command containing a phone number"
- The solution source code template `regular-chatbot.jq` describes the input as "number"
- The "well-formatted" test cases partially agree with the instructions, passing phrases, but only one of those is a "chatbot" command
- The "ill-formatted" test cases only pass numbers, not phrases.

Assuming "phrase containing phone number" is the desired description, some simplification of where in the input to find the number would better fit this level of exercise, such as requiring exactly `Call me at <phone number>`, otherwise `Hello chatbot, Happy 2024! My digits are (+1) 123-456-7890` is difficult to parse for (and capture) the ill-formatted number.

**Comment by phineas42** [comment]
I think that the best solution would be to mirror the javascript track's implementation: to assume that the whole input string represents the phone number.

**Comment by IsaacG** [comment]
Please use the forums to discuss exercise changes, not GitHub issues!
Thanks for your interest and initiative, though! This issue would be good to clear up.
