### ISSUE TITLE
jq version requirements should be noted for likely incompatibilities

### ISSUE THREAD

**Issue by phineas42** [exercism/jq#209]
The latest Ubuntu (23.10) has jq 1.6.

The regular-chatbot exercise documents at least one feature that requires jq 1.7 (the scan/2 function).

It would be helpful to put a blockquote warning in the instructions for cases where current popular operating systems are likely to encounter issues.

**Comment by IsaacG** [comment]
Feel free to discuss on the forum.

**Comment by glennj** [comment]
FYI I am working on some minor changes for this. For example, https://github.com/exercism/jq/blob/904e700aeeba9d6061267465c7971c19a47ef90b/concepts/regular-expressions/introduction.md?plain=1#L122 -- the `scan([regex, flags])` form is not implemented for `scan`, only for test/match/capture.

I'll drop a PR soon and add you both as reviewers.
