### ISSUE TITLE
Write docs for `basics` concept exercise.

### ISSUE THREAD

**Issue by glennj** [exercism/jq#8]
This exercise needs:

* a story
* a new name that aligns with the story
* new JSON data that is not the two-fer config.json

**Comment by glennj** [comment]
Perhaps, since this is a precursor to the lasagna exercise, a story can be made about a grocery list and shopping for ingredients.

**Comment by glennj** [comment]
There is some discussion in PR #7

**Comment by iHiD** [comment]
> Perhaps, since this is a precursor to the lasagna exercise, a story can be made about a grocery list and shopping for ingredients.

Love it :D

**Comment by iHiD** [comment]
(Just a CC to @kytrinyx to lurk, as she's keeping an eye on tracks that are building concept trees so we can try and find ways to make it easier for everyone)
