### ISSUE TITLE
Write docs for `lasagna` concept exercise.

### ISSUE THREAD

**Issue by glennj** [exercism/jq#9]

**Comment by DevanshRawat28671** [comment]
Hello @glennj ,

Do you mind giving some clarity on what it is exactly that is required? I just completed the `lasagna` exercise, and the docs look pretty fine to me.

**Comment by glennj** [comment]
Hi @DevanshRawat28671 

We're developing a language track for `jq`. This exercise is intended to teach the concept of variables in `jq`.

In which language did you recently complete lasagna?

**Comment by DevanshRawat28671** [comment]
Hi @glennj ,
I recently completed lasagna in your Python language track.
I think I can help with the documentation.

**Comment by glennj** [comment]
How comfortable are you with the `jq` language?

**Comment by DevanshRawat28671** [comment]
I'm pretty good actually

**Comment by DevanshRawat28671** [comment]
Just gimme a day or two.

**Comment by glennj** [comment]
I'm happy to work with you but I'll get you to do some homework first:

* get up to speed with the content of the repo: read the files in the `docs/` directory, 
* take a good look at PR #17,
* look at the existing `exercises/concept/lasagna/.meta/exemplar.jq` and `exercises/concept/lasagna/test-lasagna.bats` to see how we want to teach jq variables.

That will give you an overview of the approach we're taking on this track.

Then add your ideas for documentation here in this issue.
